spring:
  application:
    name: chachkie
---
spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: root
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  profiles: cloud
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl"
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL57Dialect"
        query:
          startup_check: "false"

